' Gambas class file

' GauchoCAD
' A simple CAD made in Gambas
'
' Copyright (C) Ing Martin P Cristia
'
' This program is free software; you can redistribute it and/or modify
' it under the terms of the GNU General Public License as published by
' the Free Software Foundation; either version 3 of the License, or
' (at your option) any later version.
'
' This program is distributed in the hope that it will be useful,
' but WITHOUT ANY WARRANTY; without even the implied warranty of
' MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
' GNU General Public License for more details.
'
' You should have received a copy of the GNU General Public License
' along with this program; if not, write to the Free Software
' Foundation, Inc., 51 Franklin St, Fifth Floor,
' Boston, MA  02110-1301  USA
Create Static



Public Const Gender As String = "Dimension"
Public Const DrawingOrder As Integer = 100 ' 1 a 32.724 esto debe Drawse primero y ser sobreescrito por el resto
Public Const PointsToDraw As Integer = 1             ' minimal point requered for drawing something usefull
Public Const HelperTrabajo As String = ("Insert an acotation")
Public ParamType As String = "TPP"                             ' that is Point, Point, Float; could be Color Text, etc
Public ParamHelper As String = "Start point;End point"
Public Const USEWITH As String = ""
Public Const OrthogonalIgnored As Boolean = False
Public Const OrthogonalForced As Boolean = False
Public Const ParamDefault As String = " "
Public Const StretchAble As Boolean = True           ' Si lo puedo deformar
Public Selected As Boolean

Public DrawAble As Boolean = False          ' True si durante la construccion ya tiene suficientes elementos para poder hacer una representacion digna
Public Visible As Boolean = True            ' si esta entidad puede ser mostrada independientmente
Public Finished As Boolean = False          ' colocar en true cuando se llegue a completar
Public StepsDone As Integer                 ' esto lo cambia cls ElementBuilder durante la construccion

Public TotalDimensions As Integer           ' the total dimensions present in this drawing

' dimstyle: Todas las variables numericas Float estaran multiplicadas por DimScale
Public DimType As Integer = 0            ' = fParam[0] and &X1111
Public DimAtatchPoint As Integer = 2     ' = fParam[1]
Public DimScale As Integer = 1           ' = fParam[2]
Public DimFormat As String = "0.00"      '
Public DimFormatAng As String = "0.0"    '
Public DimArrowSize As Float = 0.3       ' el largo de la flecha
Public DimArrowWidth As Float = 0.1      ' ancho de la flecha
Public DimTickSize As Float = 0.3        ' el tamaÃ±o de la diagonal
Public DimArrowOrThick As Boolean = True ' flecha (True) o diagonal (False)
Public DimTextHeight As Float = 0.3      '
Public DimSeparation As Float = 0.5      ' la separacion entre el punto que define la cota y el inicio de la linea q marca inicio y fin
Public DimExtension As Float = 0.5       ' la continuacion de esas lineas

' Pixeles

Public LastMouseDownX As Integer    ' change in MouseDown
Public LastMouseDownY As Integer
Public SelStartX As Integer         ' change in MouseDown
Public SelStartY As Integer
Public SelEndX As Integer           ' change in MouseMove/MouseUp
Public SelEndY As Integer

' Metros
Public SelStartXr As Float          ' Seleccion libre rectangular
Public SelStartZr As Float          ' en metros
Public SelEndXr As Float            ' aca Y es Z
Public SelEndZr As Float

' Clicks en Metros
Public ClickXr As Float
Public ClickYr As Float
Public ClickPrevXr As Float
Public ClickPrevYr As Float

Public TextEntry As String

' indicadores
'Public elem.StepsDone As Integer = 0          ' La cantidad de puntos que marco para el trabajo actual--->Gurdado en la entidad
Public StepsTotal As Integer = 0          ' Tomado de la lista de tipo de paramtros
Public PointsTotal As Integer = 0          ' Tomado de la lista de tipo de paramtros
Public NextParamType As String          ' What kind of input the element expects P=point, F=float, C=color, S=string, M=mixed either Point, or Float that is taken from Max(Px-Px', Pz-Pz')
Public ParamHelperList As String[]

' indices de valores ingresados
Public iPoints As Integer
Public iFloat As Integer
Public iString As Integer

' conserva los ultimos valores del mouse
Public CursorX As Integer
Public CursorY As Integer

Public elem As Entity

Public PoiChecking As Boolean = True
Public EntityChecking As Boolean = False
Public LastEntity As Entity

Public XYreal As Float[]

Public extension As Float
Public iBloque As Integer

' Para mejor generalidad y para compatibilidad futura usaremos los P[] asi con los CODE del DXF
' P[] = DXF CODE
' 0 = 10
' 1 = 20
' 2 = 30    Definition points
' 3 = 11
' 4 = 12
' ......
' 20 = 36

' 21 = 210
' 22 = 220	Extrusion direction(Optional ; Default = 0, 0, 1)
' 23 = 230

' fParam[] = DXF CODE
' se usara asi
' 0 =  70, Dimension type:  Values 0 - 6 are integer values that represent the dimension type.Values 32, 64, And 128 are bit values, which are added To the integer values(value 32 Is Always set In R13 And later releases)
'       0 = Rotated; 1 = Aligned; 2 = Angular; 3 = Diameter; 4 = Radius; 5 = Angular3point; 6 = Ordinate
'       32 = Indicates that the block reference(group code 2) Is Referenced by this dimension only
'       64 = Ordinate type.This Is A bit value(bit 7)used only With integer value 6. If set, ordinate Is X - type; If Not set, ordinate Is Y - type
'       128 = This Is A bit value(bit 8)added To the other group 70 values If the dimension text has been positioned at a user - defined location rather than at the Default location
'
' 1 =  71 Attachment point:
'       1 = Top left ; 2 = Top center; 3 = Top right; 4 = Middle left; 5 = Middle center; 6 = Middle right; 7 = Bottom left; 8 = Bottom center; 9 = Bottom right

' 2 = DimScale

'' Mode = DimType ver gcd.DimXXXX constants
Public Function Start(Optional Mode As Integer = gcd.dimRadius)

  Dim newBlock As New Block, eParte As Entity
  Dim f1, f2 As New Float[]

  Inc TotalDimensions

  elem = New Entity

  Me.DimType = Mode

  elem.Gender = Me.Gender
  elem.ClassHandler = cadDim
  elem.p.Resize(24)
  elem.fParam.Resize(6)
  elem.Visible = False

  ' como esto sera tratado como un inserto
  elem.fParam[0] = 1  ' scaleX
  elem.fParam[1] = 1  ' scaleY
  elem.fParam[2] = 0  ' rotate

  StepsDone = 0
  iPoints = 0

  ' init arrays
  Select Case DimType
    Case -1                 ' tengo que pregunta que dim quiere
      clsDrawingAids.HelperTrabajo = "DimType? Horizontal;Vertical;Aligned;aNgular;rOtated,Radial;Diameter"
      NextParamType = "T"

    Case gcd.DimAligned
      Me.StepsTotal = 3 ' 1-punto 2-punto 3-ubicacion del texto
      NextParamType = "P"
      ' ahora creo el bloque asociado
      newBlock.entities = New Entity[]
      newBlock.name = "*D" & Str$(gcd.CurrentDrawing.arrBlocks.Count)
      gcd.CurrentDrawing.arrBlocks.Add(newBlock)
      ' linea principal
      gcd.AddLine(newBlock.entities, [0, 0, 0, 0], elem.colour, elem.LineWidth, elem.LineType, elem.Layer, newBlock.name)

      ' lineas de demarcacion
      gcd.AddLine(newBlock.entities, [0, Me.DimExtension, 0, -Me.DimExtension], elem.colour, elem.LineWidth, elem.LineType, elem.Layer, newBlock.name)
      gcd.AddLine(newBlock.entities, [0, Me.DimExtension, 0, -Me.DimExtension], elem.colour, elem.LineWidth, elem.LineType, elem.Layer, newBlock.name)

      ' flechas

      f1.Insert([0, 0, Me.DimArrowSize, Me.DimArrowWidth, Me.DimArrowSize, -Me.DimArrowWidth, 0, 0])
      f2.Insert([0, 0, -Me.DimArrowSize, Me.DimArrowWidth, -Me.DimArrowSize, -Me.DimArrowWidth, 0, 0])

      gcd.Addsolid(newBlock.entities, f1, elem.colour, elem.LineWidth, elem.LineType, elem.Layer, newBlock.name)
      gcd.Addsolid(newBlock.entities, f2, elem.colour, elem.LineWidth, elem.LineType, elem.Layer, newBlock.name)

      ' texto
      gcd.AddMText(newBlock.entities, [0, 0, 0, 0], 0, Me.DimTextHeight, "0.00", elem.colour, elem.LineWidth, elem.LineType, elem.Layer, newBlock.name)

      ' y ahora e

    Case gcd.dimAngular

      Me.StepsTotal = 4 ' 1-centro 2-punto 3-punto 4-ubicacion del texto
      NextParamType = "P"

      ' ahora creo el bloque asociado
      newBlock.entities = New Entity[]
      newBlock.name = "*D" & Str$(gcd.CurrentDrawing.arrBlocks.Count)
      gcd.CurrentDrawing.arrBlocks.Add(newBlock)
      ' la linea principal ahora es un arco
      gcd.Addarc(newBlock.entities, [0, 0], 0, 0, 0, elem.colour, elem.LineWidth, elem.LineType, elem.Layer, newBlock.name)

      ' lineas de demarcacion
      gcd.AddLine(newBlock.entities, [0, Me.DimExtension, 0, -Me.DimExtension], elem.colour, elem.LineWidth, elem.LineType, elem.Layer, newBlock.name)
      gcd.AddLine(newBlock.entities, [0, Me.DimExtension, 0, -Me.DimExtension], elem.colour, elem.LineWidth, elem.LineType, elem.Layer, newBlock.name)

      ' flechas

      'f1.Insert()
      'f2.Insert([0, 0, -Me.DimArrowSize, Me.DimArrowWidth, -Me.DimArrowSize, -Me.DimArrowWidth, 0, 0])

      gcd.Addsolid(newBlock.entities, [0, 0, Me.DimArrowSize, Me.DimArrowWidth, Me.DimArrowSize, -Me.DimArrowWidth, 0, 0], elem.colour, elem.LineWidth, elem.LineType, elem.Layer, newBlock.name)
      gcd.Addsolid(newBlock.entities, [0, 0, -Me.DimArrowSize, Me.DimArrowWidth, -Me.DimArrowSize, -Me.DimArrowWidth, 0, 0], elem.colour, elem.LineWidth, elem.LineType, elem.Layer, newBlock.name)

      ' texto
      gcd.AddMText(newBlock.entities, [0, 0, 0, 0], 0, Me.DimTextHeight, "0.00", elem.colour, elem.LineWidth, elem.LineType, elem.Layer, newBlock.name)

    Case gcd.dimRadius

      Me.StepsTotal = 2 ' 1-centro 2-punto
      NextParamType = "P"

      ' ahora creo el bloque asociado
      newBlock.entities = New Entity[]
      newBlock.name = "*D" & Str$(gcd.CurrentDrawing.arrBlocks.Count)
      gcd.CurrentDrawing.arrBlocks.Add(newBlock)

      ' linea principal
      gcd.AddLine(newBlock.entities, [0, 0, 0, 0], elem.colour, elem.LineWidth, elem.LineType, elem.Layer, newBlock.name)

      ' linea de demarcacion
      gcd.AddLine(newBlock.entities, [0, Me.DimExtension, 0, -Me.DimExtension], elem.colour, elem.LineWidth, elem.LineType, elem.Layer, newBlock.name)

      ' flecha

      gcd.Addsolid(newBlock.entities, [0, 0, -Me.DimArrowSize, Me.DimArrowWidth, -Me.DimArrowSize, -Me.DimArrowWidth, 0, 0], elem.colour, elem.LineWidth, elem.LineType, elem.Layer, newBlock.name)

      ' texto
      gcd.AddMText(newBlock.entities, [0, 0, 0, 0], 0, Me.DimTextHeight, "0.00", elem.colour, elem.LineWidth, elem.LineType, elem.Layer, newBlock.name)

    Case gcd.dimDiameter

      Me.StepsTotal = 2 ' 1-quadrant 2-quadrant
      NextParamType = "P"

      ' ahora creo el bloque asociado
      newBlock.entities = New Entity[]
      newBlock.name = "*D" & Str$(gcd.CurrentDrawing.arrBlocks.Count)
      gcd.CurrentDrawing.arrBlocks.Add(newBlock)

      ' linea principal
      gcd.AddLine(newBlock.entities, [0, 0, 0, 0], elem.colour, elem.LineWidth, elem.LineType, elem.Layer, newBlock.name)

      ' flecha
      gcd.Addsolid(newBlock.entities, [0, 0, Me.DimArrowSize, Me.DimArrowWidth, Me.DimArrowSize, -Me.DimArrowWidth, 0, 0], elem.colour, elem.LineWidth, elem.LineType, elem.Layer, newBlock.name)
      gcd.Addsolid(newBlock.entities, [0, 0, -Me.DimArrowSize, Me.DimArrowWidth, -Me.DimArrowSize, -Me.DimArrowWidth, 0, 0], elem.colour, elem.LineWidth, elem.LineType, elem.Layer, newBlock.name)

      ' texto
      gcd.AddMText(newBlock.entities, [0, 0, 0, 0], 0, Me.DimTextHeight, "0.00", elem.colour, elem.LineWidth, elem.LineType, elem.Layer, newBlock.name)

  End Select

  'elem.gbcolor = appmain.CurrentColor
  elem.Block = newBlock.name

  iPoints = 0
  iFloat = 0
  iString = 0

  ' Pointstotal = elem.p.count / 2                                          ' at this point P is either set or 0 if non determined
  ' StepsTotal = Len(elem.ClassHandler.ParamType)
  '
  ' NextParamType = UCase(Mid(elem.ClassHandler.ParamType, elem.StepsDone + 1, 1))
  ' clsDrawingAids.HelperTrabajoNext = ParamHelperList[0]

  ' instructions to FCAD
  gcd.OrthogonalIgnored = Me.OrthogonalIgnored
  gcd.OrthogonalForced = Me.OrthogonalForced

  elem.layer = appmain.CurrentLayer
  elem.layerid = gcd.GetLayerID(appmain.CurrentLayer)

  clsDrawingAids.HelperTrabajo = elem.ClassHandler.HelperTrabajo

End

Public Sub Translate(e As Entity, dX As Float, dY As Float, Optional OnlySelected As Boolean = False)

  cadInsert.Translate(e, dx, dy, OnlySelected)

End

Public Sub Rotate(e As Entity, radians As Float)

  cadInsert.Rotate(e, radians)

End

Public Sub Scale(e As Entity, sX As Float, sY As Float)

  cadInsert.Scale(e, sx, sy)

End

Public Sub Draw(Optional e As Entity)

  If e Then
    cadInsert.Draw(e)
  Else

    cadInsert.Draw(elem)
  End If

End

'' A fat version of the entity
Public Sub DrawRemark(oE As Entity)

  cadInsert.DrawRemark(oe)

End

'' A fat version of the entity
Public Sub DrawSelected(oE As Entity)

  cadInsert.DrawSelected(oe)

End

Public Function KeyText(EnteredText As String) ' esta rutina es llamada por FCAD en el evento FCAD_KeyPress cuando recibe una texto + <Enter>

  ' this could be many things, but lets concentrate in what to expect and check if its correct
  ' The element provides a constant called ParamType wich is a string like "PPFCTB"
  ' P = point in X,Y format with decimal point as dot "."
  '     it can also be @X,Y wich means that the coordinates are relative to the last point
  ' F = float, thats any number
  ' T = a text or a single character too
  ' C = color input
  ' B = boolean, Yes/Si or No
  ' Lets see what are we expecting
  Dim Xt, Zt As Float, ErrTxt As String, Relative As Boolean

  Select Case NextParamType

    Case "P", "+"
      errtxt = ", expected a valid point like 12.4,9.5  or @12.34,10.5"
      ' lets filter
      EnteredText = Trim$(UCase$(EnteredText))
      ' So we expect a position x,y , but in some cases it can be
      ' C = close
      ' U = undo, delete last segment
      ' and others

      If Left(EnteredText, 1) = "C" Then          ' close the element
        ' got othe first point and exit
        elem.P[iPoints * 2] = elem.P[0]
        elem.P[iPoints * 2 + 1] = elem.P[1]
        Me.Finish

      Else If Left(EnteredText, 1) = "U" Then     ' undo last command and go

        elem.P.remove(elem.P.max)
        elem.P.remove(elem.P.max)
        Me.Finish
      Else                                        ' an X,Y or @X,Y

        If InStr(EnteredText, "@") > 0 Then    ' may be a point
          Relative = True
          EnteredText = Replace(EnteredText, "@", "")
        Endif
        Xt = CFloat(Split(EnteredText, ",")[0])
        Zt = CFloat(Split(EnteredText, ",")[1])

        ' if we are stll here, input was good
        elem.P[iPoints * 2] = Xt
        elem.P[iPoints * 2 + 1] = Zt

        If Relative And (elem.P.count > 2) Then
          elem.P[iPoints * 2] += elem.P[(iPoints - 1) * 2]
          elem.P[iPoints * 2 + 1] += elem.P[(iPoints - 1) * 2 + 1]

        Endif
        Inc iPoints
        AdvanceStep

      End If

    Case "T"
      errtxt = ", expected text, not a point"

      TextEntry = EnteredText

      AdvanceStep

    Case "F", "M", "A", "L"                 ' Float, Mixed, Angle, Longitud
      errtxt = "enter a valid text size"

      If EnteredText = "" Then

        Try elem.fParam[iFloat] = ParamDefault[elem.StepsDone]

      Else

        elem.fParam[iFloat] = CFloat(EnteredText)

      Endif

      Inc iFloat
      AdvanceStep

    Case "C"                                ' color
      If Dialog.SelectColor() Then
        elem.fParam[iFloat] = CFloat(Dialog.Color)
        Inc iFloat
        AdvanceStep

      Endif
      Key.Cod

  End Select

Finally

  Return

Catch

  ' unexpected input
  clsDrawingAids.ErrorMessage = ("Bad input" & ErrTxt)

End

Public Sub ReBuildBlock()

  Dim d As Float, flxTextExt As Float[]
  Dim fRotXY As Float[]

  ' -> el bloque
  iBloque = clsEntities.FIndBlockID(elem.Block)

  Select Case DimType
    Case -1 'clsDrawingAids.HelperTrabajo = "DimType? Horizontal;Vertical;Aligned;aNgular;rOtated,Radial;Diameter"
      Select Case UCase(TextEntry)
        Case "H"
          DimType = gcd.dimHorizontal
        Case "V"
          DimType = gcd.dimVertical
        Case "A"
          DimType = gcd.dimAligned
        Case "N"
          DimType = gcd.dimAngular
        Case "O"
          DimType = gcd.dimRotated
        Case "R"
          DimType = gcd.dimRadius
        Case "D"
          DimType = gcd.dimDiameter
        Case Else
          clsDrawingAids.ErrorMessage = ("Bad input")
          Return
      End Select
      ' good input

    Case gcd.DimAligned
      If iPoints = 0 Then     ' marco el primer punto
        elem.P[0] = ClickXr     ' posicion base del inserto
        elem.P[1] = ClickYr

        elem.fParam[0] = 1      ' ScaleX del inserto
        elem.fParam[1] = 1      ' ScaleY del inserto
        elem.fParam[2] = 0      ' degAngle del inserto

      Else If iPoints = 1 Then ' marco el segundo punto, lo que modifica los parametros del bloque
        elem.Visible = True
        elem.P[2] = ClickXr     ' posicion base del inserto
        elem.P[3] = ClickYr

        ' el largo de la linea principal viene dado por la distancia entre ambos puntos
        d = puntos.distancia(elem.P[0], elem.P[1], ClickXr, ClickYr)

        ' con este click calculo el angulo
        elem.fParam[2] = Ang(ClickXr - elem.P[0], ClickYr - elem.P[1]) * 180 / Pi

        ' la primer entidad del bloque es la linea principal
        gcd.CurrentDrawing.arrBlocks[iBloque].entities[0].P[0] = 0           ' X0
        gcd.CurrentDrawing.arrBlocks[iBloque].entities[0].P[1] = 0           ' Y0

        gcd.CurrentDrawing.arrBlocks[iBloque].entities[0].P[2] = d           ' X1
        gcd.CurrentDrawing.arrBlocks[iBloque].entities[0].P[3] = 0           ' Y1

        ' la segunda es la primer linea de demarcacion (sin cambios)
        'gcd.CurrentDrawing.arrBlocks[iBloque].entities[1].P[0] = 0           ' X0
        'gcd.CurrentDrawing.arrBlocks[iBloque].entities[1].P[1] = 0           ' Y0

        'gcd.CurrentDrawing.arrBlocks[iBloque].entities[1].P[2] = d           ' X1
        'gcd.CurrentDrawing.arrBlocks[iBloque].entities[1].P[3] = 0           ' Y1

        ' la tercera es la segunda linea de demarcacion
        gcd.CurrentDrawing.arrBlocks[iBloque].entities[2].P[0] = d           ' X0
        'gcd.CurrentDrawing.arrBlocks[iBloque].entities[2].P[1] = 0           ' Y0

        gcd.CurrentDrawing.arrBlocks[iBloque].entities[2].P[2] = d           ' X1
        'gcd.CurrentDrawing.arrBlocks[iBloque].entities[2].P[3] = 0           ' Y1

        ' la sexta es el texto
        gcd.CurrentDrawing.arrBlocks[iBloque].entities[5].StringData[0] = Format(d, Me.DimFormat)

        flxTextExt = glPlus.MTextExtends(gcd.CurrentDrawing.arrBlocks[iBloque].entities[5].StringData[0], 0, 0, gcd.CurrentDrawing.arrBlocks[iBloque].entities[5].fParam[1])

        ' la cuarta y quinta son las flechas , tengo que verificar si entran, o el texto
        If flxTextExt[2] * 1.1 > d Then                      ' no entra

          gcd.CurrentDrawing.arrBlocks[iBloque].entities[3].P[0] = d           ' X0
          gcd.CurrentDrawing.arrBlocks[iBloque].entities[3].P[2] = Me.DimArrowSize + d           ' X0
          gcd.CurrentDrawing.arrBlocks[iBloque].entities[3].P[4] = Me.DimArrowSize + d           ' X0
          gcd.CurrentDrawing.arrBlocks[iBloque].entities[3].P[6] = d           ' X0

          gcd.CurrentDrawing.arrBlocks[iBloque].entities[4].P[0] = 0           ' X0
          gcd.CurrentDrawing.arrBlocks[iBloque].entities[4].P[2] = -Me.DimArrowSize
          gcd.CurrentDrawing.arrBlocks[iBloque].entities[4].P[4] = -Me.DimArrowSize
          gcd.CurrentDrawing.arrBlocks[iBloque].entities[4].P[6] = 0           ' X0

          ' el texto va afuera
          gcd.CurrentDrawing.arrBlocks[iBloque].entities[5].P[0] = d + Me.DimArrowSize / 2
          gcd.CurrentDrawing.arrBlocks[iBloque].entities[5].P[1] = Me.DimArrowWidth

        Else                                                                ' entra
          gcd.CurrentDrawing.arrBlocks[iBloque].entities[3].P[0] = 0           ' X0
          gcd.CurrentDrawing.arrBlocks[iBloque].entities[3].P[2] = Me.DimArrowSize
          gcd.CurrentDrawing.arrBlocks[iBloque].entities[3].P[4] = Me.DimArrowSize
          gcd.CurrentDrawing.arrBlocks[iBloque].entities[3].P[6] = 0           ' X0

          gcd.CurrentDrawing.arrBlocks[iBloque].entities[4].P[0] = d           ' X0
          gcd.CurrentDrawing.arrBlocks[iBloque].entities[4].P[2] = -Me.DimArrowSize + d           ' X0
          gcd.CurrentDrawing.arrBlocks[iBloque].entities[4].P[4] = -Me.DimArrowSize + d           ' X0
          gcd.CurrentDrawing.arrBlocks[iBloque].entities[4].P[6] = d           ' X0

          ' el texto va adentro
          gcd.CurrentDrawing.arrBlocks[iBloque].entities[5].P[0] = d / 2 - flxTextExt[2] / 2
          gcd.CurrentDrawing.arrBlocks[iBloque].entities[5].P[1] = Me.DimArrowWidth

        End If

      Else If iPoints = 2 Then ' marco la extension

        extension = -puntos.PointToLineDistance([ClickXr, ClickYr], [elem.P[0], elem.P[1], elem.P[2], elem.P[3]])
        'Debug extension

        ' linea principal
        gcd.CurrentDrawing.arrBlocks[iBloque].entities[0].P[1] = extension           ' Y0
        gcd.CurrentDrawing.arrBlocks[iBloque].entities[0].P[3] = extension           ' Y1

        ' linea de demarcacion
        gcd.CurrentDrawing.arrBlocks[iBloque].entities[1].P[1] = Me.DimExtension + extension           ' Y0
        gcd.CurrentDrawing.arrBlocks[iBloque].entities[1].P[3] = -Me.DimExtension + extension           ' Y1

        ' segunda linea de demarcacion
        gcd.CurrentDrawing.arrBlocks[iBloque].entities[2].P[1] = Me.DimExtension + extension           ' Y0
        gcd.CurrentDrawing.arrBlocks[iBloque].entities[2].P[3] = -Me.DimExtension + extension           ' Y1

        ' texto
        gcd.CurrentDrawing.arrBlocks[iBloque].entities[5].P[1] = Me.DimArrowWidth + extension

        ' flechas
        gcd.CurrentDrawing.arrBlocks[iBloque].entities[3].P[1] = extension           ' X0
        gcd.CurrentDrawing.arrBlocks[iBloque].entities[3].P[3] = extension + Me.DimArrowWidth
        gcd.CurrentDrawing.arrBlocks[iBloque].entities[3].P[5] = extension - Me.DimArrowWidth
        gcd.CurrentDrawing.arrBlocks[iBloque].entities[3].P[7] = extension           ' X0

        gcd.CurrentDrawing.arrBlocks[iBloque].entities[4].P[1] = extension           ' X0
        gcd.CurrentDrawing.arrBlocks[iBloque].entities[4].P[3] = extension + Me.DimArrowWidth
        gcd.CurrentDrawing.arrBlocks[iBloque].entities[4].P[5] = extension - Me.DimArrowWidth
        gcd.CurrentDrawing.arrBlocks[iBloque].entities[4].P[7] = extension           ' X0

      End If

    Case gcd.dimAngular
      If iPoints = 0 Then     ' marco el primer punto
        elem.P[0] = ClickXr     ' posicion base del inserto
        elem.P[1] = ClickYr

        elem.fParam[0] = 1      ' ScaleX del inserto
        elem.fParam[1] = 1      ' ScaleY del inserto
        elem.fParam[2] = 0      ' degAngle del inserto

      Else If iPoints = 1 Then ' marco el segundo punto, lo que modifica los parametros del bloque

        elem.P[2] = ClickXr     ' con esto puedo definir el radio del arco
        elem.P[3] = ClickYr
        d = puntos.distancia(elem.P[0], elem.P[1], ClickXr, ClickYr)

        ' con este click calculo el angulo
        'elem.fParam[2] = Ang(ClickXr - elem.P[0], ClickYr - elem.P[1]) * 180 / Pi

        ' la primer entidad del bloque es el arco
        gcd.CurrentDrawing.arrBlocks[iBloque].entities[0].P[0] = 0 'elem.P[0]
        gcd.CurrentDrawing.arrBlocks[iBloque].entities[0].P[1] = 0 'elem.P[1]

        gcd.CurrentDrawing.arrBlocks[iBloque].entities[0].fParam[0] = d          ' radio
        gcd.CurrentDrawing.arrBlocks[iBloque].entities[0].fParam[1] = Ang(ClickXr - elem.P[0], ClickYr - elem.P[1]) * 180 / Pi
        gcd.CurrentDrawing.arrBlocks[iBloque].entities[0].fParam[2] = 0

        ' las lineas de extension (las hago HORIZONTALES y las roto)
        gcd.CurrentDrawing.arrBlocks[iBloque].entities[1].P.Clear
        gcd.CurrentDrawing.arrBlocks[iBloque].entities[1].P.Insert([-Me.DimExtension, 0, Me.DimExtension, 0])
        gcd.CurrentDrawing.arrBlocks[iBloque].entities[2].P.Clear
        gcd.CurrentDrawing.arrBlocks[iBloque].entities[2].P.Insert([-Me.DimExtension, 0, Me.DimExtension, 0])

        ' flechas
        gcd.CurrentDrawing.arrBlocks[iBloque].entities[3].P.Clear
        gcd.CurrentDrawing.arrBlocks[iBloque].entities[3].P.Insert([0, 0, -Me.DimArrowWidth, Me.DimArrowSize, Me.DimArrowWidth, Me.DimArrowSize, 0, 0])

        gcd.CurrentDrawing.arrBlocks[iBloque].entities[4].P.Clear
        gcd.CurrentDrawing.arrBlocks[iBloque].entities[4].P.Insert([0, 0, -Me.DimArrowWidth, -Me.DimArrowSize, Me.DimArrowWidth, -Me.DimArrowSize, 0, 0])

        ' roto
        gcd.CurrentDrawing.arrBlocks[iBloque].entities[1].ClassHandler.Rotate(gcd.CurrentDrawing.arrBlocks[iBloque].entities[1], gcd.CurrentDrawing.arrBlocks[iBloque].entities[0].fParam[1] / 180 * Pi)
        gcd.CurrentDrawing.arrBlocks[iBloque].entities[2].ClassHandler.Rotate(gcd.CurrentDrawing.arrBlocks[iBloque].entities[2], gcd.CurrentDrawing.arrBlocks[iBloque].entities[0].fParam[1] / 180 * Pi)
        gcd.CurrentDrawing.arrBlocks[iBloque].entities[3].ClassHandler.Rotate(gcd.CurrentDrawing.arrBlocks[iBloque].entities[3], gcd.CurrentDrawing.arrBlocks[iBloque].entities[0].fParam[1] / 180 * Pi)
        gcd.CurrentDrawing.arrBlocks[iBloque].entities[4].ClassHandler.Rotate(gcd.CurrentDrawing.arrBlocks[iBloque].entities[4], gcd.CurrentDrawing.arrBlocks[iBloque].entities[0].fParam[1] / 180 * Pi)

        ' traslado
        gcd.CurrentDrawing.arrBlocks[iBloque].entities[1].ClassHandler.Translate(gcd.CurrentDrawing.arrBlocks[iBloque].entities[1], elem.P[2] - elem.P[0], elem.P[3] - elem.P[1])
        gcd.CurrentDrawing.arrBlocks[iBloque].entities[2].ClassHandler.Translate(gcd.CurrentDrawing.arrBlocks[iBloque].entities[2], elem.P[2] - elem.P[0], elem.P[3] - elem.P[1])
        gcd.CurrentDrawing.arrBlocks[iBloque].entities[3].ClassHandler.Translate(gcd.CurrentDrawing.arrBlocks[iBloque].entities[3], elem.P[2] - elem.P[0], elem.P[3] - elem.P[1])
        gcd.CurrentDrawing.arrBlocks[iBloque].entities[4].ClassHandler.Translate(gcd.CurrentDrawing.arrBlocks[iBloque].entities[4], elem.P[2] - elem.P[0], elem.P[3] - elem.P[1])

        ' la sexta es el texto
        gcd.CurrentDrawing.arrBlocks[iBloque].entities[5].StringData[0] = Format(0, Me.DimFormatAng)
        flxTextExt = glPlus.MTextExtends(gcd.CurrentDrawing.arrBlocks[iBloque].entities[5].StringData[0], 0, 0, gcd.CurrentDrawing.arrBlocks[iBloque].entities[5].fParam[1])

        gcd.CurrentDrawing.arrBlocks[iBloque].entities[5].P[0] = elem.P[2] - elem.P[0]
        gcd.CurrentDrawing.arrBlocks[iBloque].entities[5].P[1] = elem.P[3] - elem.P[1]

      Else If iPoints = 2 Then ' marco el segundo punto, lo que modifica los parametros del bloque
        elem.Visible = True
        elem.P[4] = ClickXr
        elem.P[5] = ClickYr

        'gcd.CurrentDrawing.arrBlocks[iBloque].entities[0].fParam[1] = Ang(ClickXr - elem.P[0], ClickYr - elem.P[1]) * 180 / Pi
        gcd.CurrentDrawing.arrBlocks[iBloque].entities[0].fParam[2] = Ang(ClickXr - elem.P[0], ClickYr - elem.P[1]) * 180 / Pi

        ' las lineas de extension (las hago HORIZONTALES y las roto)
        'gcd.CurrentDrawing.arrBlocks[iBloque].entities[1].P.Clear
        'gcd.CurrentDrawing.arrBlocks[iBloque].entities[1].P.Insert([-Me.DimExtension, 0, Me.DimExtension, 0])
        gcd.CurrentDrawing.arrBlocks[iBloque].entities[2].P.Clear
        gcd.CurrentDrawing.arrBlocks[iBloque].entities[2].P.Insert([-Me.DimExtension, 0, Me.DimExtension, 0])

        ' flechas
        'gcd.CurrentDrawing.arrBlocks[iBloque].entities[3].P.Clear
        'gcd.CurrentDrawing.arrBlocks[iBloque].entities[3].P.Insert([0, 0, -Me.DimArrowWidth, Me.DimArrowSize, Me.DimArrowWidth, Me.DimArrowSize, 0, 0])

        gcd.CurrentDrawing.arrBlocks[iBloque].entities[4].P.Clear
        gcd.CurrentDrawing.arrBlocks[iBloque].entities[4].P.Insert([0, 0, -Me.DimArrowWidth, -Me.DimArrowSize, Me.DimArrowWidth, -Me.DimArrowSize, 0, 0])

        ' roto

        'gcd.CurrentDrawing.arrBlocks[iBloque].entities[1].ClassHandler.Rotate(gcd.CurrentDrawing.arrBlocks[iBloque].entities[1], gcd.CurrentDrawing.arrBlocks[iBloque].entities[0].fParam[1] / 180 * Pi)
        gcd.CurrentDrawing.arrBlocks[iBloque].entities[2].ClassHandler.Rotate(gcd.CurrentDrawing.arrBlocks[iBloque].entities[2], gcd.CurrentDrawing.arrBlocks[iBloque].entities[0].fParam[2] / 180 * Pi)
        'gcd.CurrentDrawing.arrBlocks[iBloque].entities[3].ClassHandler.Rotate(gcd.CurrentDrawing.arrBlocks[iBloque].entities[3], gcd.CurrentDrawing.arrBlocks[iBloque].entities[0].fParam[1] / 180 * Pi)
        gcd.CurrentDrawing.arrBlocks[iBloque].entities[4].ClassHandler.Rotate(gcd.CurrentDrawing.arrBlocks[iBloque].entities[4], gcd.CurrentDrawing.arrBlocks[iBloque].entities[0].fParam[2] / 180 * Pi)

        ' muevo
        fRotXY = puntos.RotateFromPointWithAngle(elem.P[0], elem.P[1], (gcd.CurrentDrawing.arrBlocks[iBloque].entities[0].fParam[2] - gcd.CurrentDrawing.arrBlocks[iBloque].entities[0].fParam[1]) / 180 * Pi, elem.P[2], elem.P[3])

        'gcd.CurrentDrawing.arrBlocks[iBloque].entities[2].ClassHandler.Translate(gcd.CurrentDrawing.arrBlocks[iBloque].entities[2], elem.P[4] - elem.P[0], elem.P[5] - elem.P[1])
        'gcd.CurrentDrawing.arrBlocks[iBloque].entities[4].ClassHandler.Translate(gcd.CurrentDrawing.arrBlocks[iBloque].entities[4], elem.P[4] - elem.P[0], elem.P[5] - elem.P[1])
        gcd.CurrentDrawing.arrBlocks[iBloque].entities[2].ClassHandler.Translate(gcd.CurrentDrawing.arrBlocks[iBloque].entities[2], fRotXY[0] - elem.P[0], fRotXY[1] - elem.P[1])
        gcd.CurrentDrawing.arrBlocks[iBloque].entities[4].ClassHandler.Translate(gcd.CurrentDrawing.arrBlocks[iBloque].entities[4], fRotXY[0] - elem.P[0], fRotXY[1] - elem.P[1])

        ' la sexta es el texto
        If (gcd.CurrentDrawing.arrBlocks[iBloque].entities[0].fParam[2] - gcd.CurrentDrawing.arrBlocks[iBloque].entities[0].fParam[1]) < 0 Then gcd.CurrentDrawing.arrBlocks[iBloque].entities[0].fParam[2] += 360
        gcd.CurrentDrawing.arrBlocks[iBloque].entities[5].StringData[0] = Format((gcd.CurrentDrawing.arrBlocks[iBloque].entities[0].fParam[2] - gcd.CurrentDrawing.arrBlocks[iBloque].entities[0].fParam[1]), Me.DimFormatAng)
        fRotXY = puntos.RotateFromPointWithAngle(elem.P[0], elem.P[1], (gcd.CurrentDrawing.arrBlocks[iBloque].entities[0].fParam[2] - gcd.CurrentDrawing.arrBlocks[iBloque].entities[0].fParam[1]) / 180 * Pi / 2, elem.P[2], elem.P[3])

        flxTextExt = glPlus.MTextExtends(gcd.CurrentDrawing.arrBlocks[iBloque].entities[5].StringData[0], 0, 0, gcd.CurrentDrawing.arrBlocks[iBloque].entities[5].fParam[1])

        gcd.CurrentDrawing.arrBlocks[iBloque].entities[5].P[0] = fRotXY[0] - elem.P[0]
        gcd.CurrentDrawing.arrBlocks[iBloque].entities[5].P[1] = fRotXY[1] - elem.P[1]
        gcd.CurrentDrawing.arrBlocks[iBloque].entities[5].fParam[0] = (gcd.CurrentDrawing.arrBlocks[iBloque].entities[0].fParam[2] + gcd.CurrentDrawing.arrBlocks[iBloque].entities[0].fParam[1]) / 2 - 90

      Else If iPoints = 3 Then ' aca marco la extension, que es todo lo anterior, pero con otro radio

        elem.P[6] = ClickXr
        elem.P[7] = ClickYr

        ' nuevo radio
        d = puntos.distancia(elem.P[0], elem.P[1], ClickXr, ClickYr)
        gcd.CurrentDrawing.arrBlocks[iBloque].entities[0].fParam[0] = d          ' radio del arco

        ' regenero

        ' las lineas de extension (las hago HORIZONTALES y las roto)
        gcd.CurrentDrawing.arrBlocks[iBloque].entities[1].P.Clear
        gcd.CurrentDrawing.arrBlocks[iBloque].entities[1].P.Insert([-Me.DimExtension, 0, Me.DimExtension, 0])
        gcd.CurrentDrawing.arrBlocks[iBloque].entities[2].P.Clear
        gcd.CurrentDrawing.arrBlocks[iBloque].entities[2].P.Insert([-Me.DimExtension, 0, Me.DimExtension, 0])

        ' flechas
        gcd.CurrentDrawing.arrBlocks[iBloque].entities[3].P.Clear
        gcd.CurrentDrawing.arrBlocks[iBloque].entities[3].P.Insert([0, 0, -Me.DimArrowWidth, Me.DimArrowSize, Me.DimArrowWidth, Me.DimArrowSize, 0, 0])

        gcd.CurrentDrawing.arrBlocks[iBloque].entities[4].P.Clear
        gcd.CurrentDrawing.arrBlocks[iBloque].entities[4].P.Insert([0, 0, -Me.DimArrowWidth, -Me.DimArrowSize, Me.DimArrowWidth, -Me.DimArrowSize, 0, 0])

        ' roto
        gcd.CurrentDrawing.arrBlocks[iBloque].entities[1].ClassHandler.Rotate(gcd.CurrentDrawing.arrBlocks[iBloque].entities[1], gcd.CurrentDrawing.arrBlocks[iBloque].entities[0].fParam[1] / 180 * Pi)
        gcd.CurrentDrawing.arrBlocks[iBloque].entities[2].ClassHandler.Rotate(gcd.CurrentDrawing.arrBlocks[iBloque].entities[2], gcd.CurrentDrawing.arrBlocks[iBloque].entities[0].fParam[2] / 180 * Pi)
        gcd.CurrentDrawing.arrBlocks[iBloque].entities[3].ClassHandler.Rotate(gcd.CurrentDrawing.arrBlocks[iBloque].entities[3], gcd.CurrentDrawing.arrBlocks[iBloque].entities[0].fParam[1] / 180 * Pi)
        gcd.CurrentDrawing.arrBlocks[iBloque].entities[4].ClassHandler.Rotate(gcd.CurrentDrawing.arrBlocks[iBloque].entities[4], gcd.CurrentDrawing.arrBlocks[iBloque].entities[0].fParam[2] / 180 * Pi)

        ' muevo
        fRotXY = puntos.RotateFromPointWithAngle(elem.P[0], elem.P[1], gcd.CurrentDrawing.arrBlocks[iBloque].entities[0].fParam[1] / 180 * Pi, d + elem.P[0], elem.P[1])
        ' traslado una flecha y una linea de extension
        gcd.CurrentDrawing.arrBlocks[iBloque].entities[1].ClassHandler.Translate(gcd.CurrentDrawing.arrBlocks[iBloque].entities[1], fRotXY[0] - elem.P[0], fRotXY[1] - elem.P[1])
        gcd.CurrentDrawing.arrBlocks[iBloque].entities[3].ClassHandler.Translate(gcd.CurrentDrawing.arrBlocks[iBloque].entities[3], fRotXY[0] - elem.P[0], fRotXY[1] - elem.P[1])

        ' muevo
        fRotXY = puntos.RotateFromPointWithAngle(elem.P[0], elem.P[1], gcd.CurrentDrawing.arrBlocks[iBloque].entities[0].fParam[2] / 180 * Pi, d + elem.P[0], elem.P[1])
        ' traslado las otras
        gcd.CurrentDrawing.arrBlocks[iBloque].entities[2].ClassHandler.Translate(gcd.CurrentDrawing.arrBlocks[iBloque].entities[2], fRotXY[0] - elem.P[0], fRotXY[1] - elem.P[1])
        gcd.CurrentDrawing.arrBlocks[iBloque].entities[4].ClassHandler.Translate(gcd.CurrentDrawing.arrBlocks[iBloque].entities[4], fRotXY[0] - elem.P[0], fRotXY[1] - elem.P[1])

        ' la sexta es el texto

        fRotXY = puntos.RotateFromPointWithAngle(elem.P[0], elem.P[1], (gcd.CurrentDrawing.arrBlocks[iBloque].entities[0].fParam[2] + gcd.CurrentDrawing.arrBlocks[iBloque].entities[0].fParam[1]) / 180 * Pi / 2, d + elem.P[0], elem.P[1])

        gcd.CurrentDrawing.arrBlocks[iBloque].entities[5].P[0] = fRotXY[0] - elem.P[0]
        gcd.CurrentDrawing.arrBlocks[iBloque].entities[5].P[1] = fRotXY[1] - elem.P[1]

      End If

    Case gcd.dimRadius
      If iPoints = 0 Then     ' marco el primer punto
        elem.P[0] = ClickXr     ' posicion base del inserto
        elem.P[1] = ClickYr

        elem.fParam[0] = 1      ' ScaleX del inserto
        elem.fParam[1] = 1      ' ScaleY del inserto
        elem.fParam[2] = 0      ' degAngle del inserto

      Else If iPoints = 1 Then ' marco el segundo punto, lo que modifica los parametros del bloque
        elem.Visible = True
        elem.P[2] = ClickXr     ' posicion base del inserto
        elem.P[3] = ClickYr

        ' el largo de la linea principal viene dado por la distancia entre ambos puntos
        d = puntos.distancia(elem.P[0], elem.P[1], ClickXr, ClickYr)

        ' con este click calculo el angulo
        elem.fParam[2] = Ang(ClickXr - elem.P[0], ClickYr - elem.P[1]) * 180 / Pi

        ' la primer entidad del bloque es la linea principal
        gcd.CurrentDrawing.arrBlocks[iBloque].entities[0].P[0] = 0           ' X0
        gcd.CurrentDrawing.arrBlocks[iBloque].entities[0].P[1] = 0           ' Y0

        gcd.CurrentDrawing.arrBlocks[iBloque].entities[0].P[2] = d           ' X1
        gcd.CurrentDrawing.arrBlocks[iBloque].entities[0].P[3] = 0           ' Y1

        ' la segunda es la primer linea de demarcacion (sin cambios)
        'gcd.CurrentDrawing.arrBlocks[iBloque].entities[1].P[0] = 0           ' X0
        'gcd.CurrentDrawing.arrBlocks[iBloque].entities[1].P[1] = 0           ' Y0

        'gcd.CurrentDrawing.arrBlocks[iBloque].entities[1].P[2] = d           ' X1
        'gcd.CurrentDrawing.arrBlocks[iBloque].entities[1].P[3] = 0           ' Y1

        ' la sexta es el texto
        gcd.CurrentDrawing.arrBlocks[iBloque].entities[3].StringData[0] = Format(d, Me.DimFormat)

        flxTextExt = glPlus.MTextExtends(gcd.CurrentDrawing.arrBlocks[iBloque].entities[3].StringData[0], 0, 0, gcd.CurrentDrawing.arrBlocks[iBloque].entities[3].fParam[1])

        ' la tercera es una flecha

        gcd.CurrentDrawing.arrBlocks[iBloque].entities[2].P[0] = d           ' X0
        gcd.CurrentDrawing.arrBlocks[iBloque].entities[2].P[2] = -Me.DimArrowSize + d           ' X0
        gcd.CurrentDrawing.arrBlocks[iBloque].entities[2].P[4] = -Me.DimArrowSize + d           ' X0
        gcd.CurrentDrawing.arrBlocks[iBloque].entities[2].P[6] = d           ' X0

        ' el texto va adentro
        gcd.CurrentDrawing.arrBlocks[iBloque].entities[3].P[0] = d / 2 - flxTextExt[2] / 2
        gcd.CurrentDrawing.arrBlocks[iBloque].entities[3].P[1] = Me.DimArrowWidth

      End If

    Case gcd.dimDiameter

      If iPoints = 0 Then     ' marco el primer punto
        elem.P[0] = ClickXr     ' posicion base del inserto
        elem.P[1] = ClickYr

        elem.fParam[0] = 1      ' ScaleX del inserto
        elem.fParam[1] = 1      ' ScaleY del inserto
        elem.fParam[2] = 0      ' degAngle del inserto

      Else If iPoints = 1 Then ' marco el segundo punto, lo que modifica los parametros del bloque
        elem.Visible = True
        elem.P[2] = ClickXr     ' posicion base del inserto
        elem.P[3] = ClickYr

        ' el largo de la linea principal viene dado por la distancia entre ambos puntos
        d = puntos.distancia(elem.P[0], elem.P[1], ClickXr, ClickYr)

        ' con este click calculo el angulo
        elem.fParam[2] = Ang(ClickXr - elem.P[0], ClickYr - elem.P[1]) * 180 / Pi

        ' la primer entidad del bloque es la linea principal
        gcd.CurrentDrawing.arrBlocks[iBloque].entities[0].P[0] = 0           ' X0
        gcd.CurrentDrawing.arrBlocks[iBloque].entities[0].P[1] = 0           ' Y0

        gcd.CurrentDrawing.arrBlocks[iBloque].entities[0].P[2] = d           ' X1
        gcd.CurrentDrawing.arrBlocks[iBloque].entities[0].P[3] = 0           ' Y1

        ' la sexta es el texto
        gcd.CurrentDrawing.arrBlocks[iBloque].entities[3].StringData[0] = Format(d, Me.DimFormat)

        flxTextExt = glPlus.MTextExtends(gcd.CurrentDrawing.arrBlocks[iBloque].entities[3].StringData[0], 0, 0, gcd.CurrentDrawing.arrBlocks[iBloque].entities[3].fParam[1])

        gcd.CurrentDrawing.arrBlocks[iBloque].entities[1].P[0] = 0           ' X0
        gcd.CurrentDrawing.arrBlocks[iBloque].entities[1].P[2] = Me.DimArrowSize
        gcd.CurrentDrawing.arrBlocks[iBloque].entities[1].P[4] = Me.DimArrowSize
        gcd.CurrentDrawing.arrBlocks[iBloque].entities[1].P[6] = 0           ' X0

        gcd.CurrentDrawing.arrBlocks[iBloque].entities[2].P[0] = d           ' X0
        gcd.CurrentDrawing.arrBlocks[iBloque].entities[2].P[2] = -Me.DimArrowSize + d           ' X0
        gcd.CurrentDrawing.arrBlocks[iBloque].entities[2].P[4] = -Me.DimArrowSize + d           ' X0
        gcd.CurrentDrawing.arrBlocks[iBloque].entities[2].P[6] = d           ' X0

        ' el texto va adentro
        gcd.CurrentDrawing.arrBlocks[iBloque].entities[3].P[0] = d / 2 - flxTextExt[2] / 2
        gcd.CurrentDrawing.arrBlocks[iBloque].entities[3].P[1] = Me.DimArrowWidth

      End If

  End Select

  appmain.redraw

End

Public Function MouseMove(mouseX As Integer, mouseY As Integer) ' esta rutina es llamada por FCAD en el evento DrawingArea_MouseMove

  If InStr("LAP", NextParamType) = 0 Then Return ' we are expecting a parameter

  ' if we expect a parameter, it will be passed
  If NextParamType = "A" Then

    ' return the angle from horizontal to us
    elem.fParam[iFloat] = Ang(appmain.Xreal(mouseX) - elem.p[elem.p.max - 1], appmain.Yreal(mouseY) - elem.p[elem.p.max])
    elem.fParam[iFloat] *= 180 / Pi
    appmain.redraw
    Return              ' nothing more to do here
  End If

  If NextParamType = "L" Then

    ' return the angle from horizontal to us
    elem.fParam[iFloat] = puntos.distancia(puntos.Near(appmain.Xreal(mouseX)), puntos.Near(appmain.Yreal(mouseY)), elem.p[elem.p.max - 1], elem.p[elem.p.max])

    appmain.redraw
    Return              ' nothing more to do here
  End If

  ' we are waiting for a point
  ClickXr = puntos.Near(appmain.Xreal(mouseX))
  ClickYr = puntos.Near(appmain.Yreal(mouseY))

  ' y si tengo enganche?
  If (gcd.CurrentDrawing.iEntity[2] >= 0) And (gcd.OrthogonalForced = False) Then

    ' esto re enganchado
    ClickXr = gcd.CurrentDrawing.iEntity[0]
    ClickYr = gcd.CurrentDrawing.iEntity[1]

    ' aca tengo que verificar el ortogonal
  Else If Me.StepsDone > 0 Then                                                                          ' puedo hacer ortogonal
    If gcd.OrthogonalForced Or (Not gcd.OrthogonalIgnored And gcd.Orthogonal) Then          ' hablame de operadores logicos

      If Abs(ClickXr - ClickPrevXr) > Abs(ClickYr - ClickPrevYr) Then ' prevalece X
        ClickYr = ClickPrevYr
      Else
        ClickXr = ClickPrevXr
      Endif

    End If

  End If

  RebuildBlock

  appmain.redraw

End

Public Function MouseDown(mouseX As Integer, mouseY As Integer) ' esta rutina es llamada por FCAD en el evento DrawingArea_MouseDown

  clsDrawingAids.ErrorMessage = ""
  If InStr("LAP", NextParamType) = 0 Then Return ' we are expecting a parameter

  ' if we expect a parameter, it will be passed
  If NextParamType = "A" Then

    ' return the angle from horizontal to us
    elem.fParam[iFloat] = Ang(appmain.Xreal(mouseX) - elem.p[elem.p.max - 1], appmain.Yreal(mouseY) - elem.p[elem.p.max])
    elem.fParam[iFloat] *= 180 / Pi

    Inc iFloat
    AdvanceStep
    Return              ' nothing more to do here
  End If

  If NextParamType = "L" Then

    ' return the angle from horizontal to us
    elem.fParam[iFloat] = puntos.distancia(puntos.Near(appmain.Xreal(mouseX)), puntos.Near(appmain.Yreal(mouseY)), elem.p[elem.p.max - 1], elem.p[elem.p.max])
    Inc iFloat
    AdvanceStep
    Return              ' nothing more to do here
  End If

  ' we are waiting for a point

  ClickXr = puntos.Near(appmain.Xreal(mouseX))
  ClickYr = puntos.Near(appmain.Yreal(mouseY))

  ' y si tengo enganche?

  If (gcd.CurrentDrawing.iEntity[2] >= 0) And (gcd.OrthogonalForced = False) Then

    ' esto re enganchado

    ClickXr = gcd.CurrentDrawing.iEntity[0]
    ClickYr = gcd.CurrentDrawing.iEntity[1]

    ' aca tengo que verificar el ortogonal

  Else If Me.StepsDone > 0 Then                                                                          ' puedo hacer ortogonal
    If gcd.OrthogonalForced Or (Not gcd.OrthogonalIgnored And gcd.Orthogonal) Then          ' hablame de operadores logicos

      If Abs(ClickXr - ClickPrevXr) > Abs(ClickYr - ClickPrevYr) Then ' prevalece X
        ClickYr = ClickPrevYr
      Else
        ClickXr = ClickPrevXr
      Endif

    End If

  End If

  ClickPrevXr = ClickXr
  ClickPrevYr = ClickYr

  Inc iPoints
  AdvanceStep

End

Public Function MouseUp(mouseX As Integer, mouseY As Integer) ' esta rutina es llamada por FCAD en el evento DrawingArea_MouseUp

End

Public Sub AdvanceStep()

  Inc StepsDone
  If Me.StepsDone = Me.StepsTotal Then
    clsEntityBuilder.elem = elem
    clsEntityBuilder.Finish
    elem = Null

  End If

End

Public Function Draw2(oE As Entity)

  cadInsert.Draw2(oe)

End

Public Sub CreatePolygon(oE As Entity)

  cadInsert.CreatePolygon(oe)

End

Public Function BuildPOI(oE As Entity, Optional arrIndex As Integer = -1) As Integer

  cadInsert.BuildPOI(oe, arrIndex)

End

Public Sub Cancel()

  elem = Null
  gcd.clsJobPrevious = Me
  gcd.clsJob = clsDefaultJob
  clsDrawingAids.CleanTexts
  appmain.redraw

End

' This function will return False if the element couldn't be created for some reason: bad or incomple user input
' True means all is good, False will instruct the clsEntityBuilder to delete it
Public Sub Finish(oE As Entity, Optional ParamsDone As Integer = -1) As Boolean

  ' primero agregamos la entidad al array

  cadInsert.Finish(oe, ParamsDone)

End


' "entity": "DIMENSION_LINEAR",
' "index": 262,
' "type": 21,
' "handle": [0, 3226],
' "size": 123,
' "bitsize": 872,
' "_subclass": "AcDbEntity",
' "prev_entity": [12, 1, 164, 3062],
' "next_entity": [10, 2, 577, 3803],
' "layer": [5, 2, 1883, 1883],
' "preview_exists": 0,
' "entmode": 2,
' "nolinks": 0,
' "color": 256,
' "ltype_scale": 1.0,
' "ltype_flags": 0,
' "plotstyle_flags": 0,
' "invisible": 0,
' "linewt": 29,
' "_subclass": "AcDbDimension",
' "extrusion": [0.0, 0.0, 1.0],
' "text_midpt": [217.50000000000006, 85.76276491494264],
' "elevation": 0.0,
' "flag1": 10,
' "user_text": "",
' "text_rotation": 0.0,
' "horiz_dir": 0.0,
' "ins_scale": [1.0, 1.0, 1.0],
' "ins_rotation": 0.0,
' "attachment": 5,
' "lspace_style": 1,
' "lspace_factor": 1.0,
' "act_measurement": 384.99999999999989,
' "clone_ins_pt": [0.0, 0.0],
' "flag": 128,
' "_subclass": "AcDbAlignedDimension",
' "xline1_pt": [25.0000000000001, 10.0, 0.0],
' "xline2_pt": [410.0, 10.0, 0.0],
' "def_pt": [410.0, 85.76276491494264, 0.0],
' "oblique_angle": 0.0,
' "dim_rotation": 0.0,
' "_subclass": "AcDbRotatedDimension",
' "dimstyle": [5, 1, 57, 57],
' "block": [5, 2, 3228, 3228]


' "entity": "DIMENSION_ANG3PT",
'      "index": 278,
'      "type": 23,
'      "handle": [0, 4504],
'      "size": 144,
'      "bitsize": 1010,
'      "reactors": [
'        [4, 2, 4506, 4506]
'      ],
'      "xdicobjhandle": [3, 2, 4505, 4505],
'      "_subclass": "AcDbEntity",
'      "prev_entity": [8, 0, 0, 4503],
'      "next_entity": [10, 1, 30, 4534],
'      "layer": [5, 2, 5261, 5261],
'      "preview_exists": 0,
'      "entmode": 2,
'      "nolinks": 0,
'      "color": 256,
'      "ltype_scale": 1.0,
'      "ltype_flags": 0,
'      "plotstyle_flags": 0,
'      "invisible": 0,
'      "linewt": 29,
'      "_subclass": "AcDbDimension",
'      "extrusion": [0.0, 0.0, 1.0],
'      "text_midpt": [348.21138128872752, 114.64222953967749],
'      "elevation": 0.0,
'      "flag1": 10,
'      "user_text": "",
'      "text_rotation": 0.0,
'      "horiz_dir": 0.0,
'      "ins_scale": [1.0, 1.0, 1.0],
'      "ins_rotation": 0.0,
'      "attachment": 5,
'      "lspace_style": 1,
'      "lspace_factor": 1.0,
'      "act_measurement": 0.41551576504848,
'      "clone_ins_pt": [0.0, 0.0],
'      "flag": 128,
'      "_subclass": "AcDb3PointAngularDimension",
'      "def_pt": [349.89251525148757, 115.79813193763354, 0.0],
'      "xline1_pt": [343.78242223304994, 126.27589894372454, 0.0],
'      "xline2_pt": [341.32254709690983, 120.90059947299312, 0.0],
'      "center_pt": [336.34758655818501, 133.69728917520501, 0.0],
'      "dimstyle": [5, 1, 57, 57],
'     "block": [5, 2, 4507, 4507]



' "entity": "ARC_DIMENSION",
'     "index": 287,
'     "type": 515,
'     "handle": [0, 4605],
'     "size": 1928,
'     "bitsize": 15276,
'     "preview_exists": 1,
'     "reactors": [
'       [4, 2, 4628, 4628]
'     ],
'     "xdicobjhandle": [3, 2, 4618, 4618],
'     "_subclass": "AcDbEntity",
'     "prev_entity": [12, 1, 7, 4598],
'     "next_entity": [10, 1, 125, 4730],
'     "layer": [5, 2, 5261, 5261],
'     "preview_exists": 1,
'     "preview_is_proxy": 0,
'     "preview_size": 1728,
'     "preview": "C00600003A0000000C0000001300000000000000880000001D000000000000000000F03F0000000000000000000000000000000000000000000000000000000000000000000000000000F03F0000000000000000000000000000000000000000000000000000000000000000000000000000F03F0000000000000000000000000000000000000000000000000000000000000000000000000000F03F0C000000160000000A0000C30C00000017000000FDFFFFFF0C00000012000000FF7F000054000000200000000200000060E3D71805A97840BCA6894349875F40000000000000000054A146280F1A79404B5AE0861E1A6040000000000000000000000000000000000000000000000000000000000000F03F0C000000160000000A0000C30C00000017000000FDFFFFFF0C00000012000000FF7F00005400000020000000020000001D9441992CA9774084974ED3761F5E4000000000000000004DC7BCD9F23577401AF65059628B5D40000000000000000000000000000000000000000000000000000000000000F03F0C000000160000000A0000C30C00000017000000FDFFFFFF0C00000012000000FF7F00000C0000001400000002000000640000000400000033D53981522A78408F186EB66FC55E400000000000000000E5590ECFB10A304000000000000000000000000000000000000000000000F03F00B59AAB57F72D40903577A1A6EC164000000000000000007FF0BD846EB20840000000000C000000160000000A0000C30C00000017000000FDFFFFFF0C00000012000000FE7F0000540000002000000002000000D62276BBB80F7940D9EB6C67572360400000000000000000DC32B7C1612479400FA018B9E2106040000000000000000000000000000000000000000000000000000000000000F03F0C000000160000000A0000C30C00000017000000FDFFFFFF0C00000012000000FE7F00005400000020000000020000006FA68F83E42B77407C7B366812A05D4000000000000000009DFA3A1605407740B43A634DB7765D40000000000000000000000000000000000000000000000000000000000000F03F0C00000016000000090000C30C00000017000000FDFFFFFF0C00000012000000FF7F00000C00000016000000090000C3A40000000B00000033FA93CF699F7740F2912A141A2E6140000000000000000000000000000000000000000000000000000000000000F03FF8A23A093930EE3F0E6FBFF27E3AD53F000000000000000032362C3137000000050000000100000000000000000000409A9999999999E93F0000000000000000000000000000F03F0000000000000000000000000000000000000000726F6D616E732E736878005C000000C00C00000016000000090000C30C00000017000000FDFFFFFF0C00000012000000000000000C000000140000000200000064000000040000003E4937DCAE7F77405A88857EF1126140000000000000000000E7799EE779FE3F00000000000000000000000000000000000000000000F03F00B3EE5136C0FC3F0075FFDAB537E43F0000000000000000232D4454FB210940000000000C00000016000000020000C30C00000017000000FDFFFFFF0C00000012000000FF7F00000C00000012000000000000000C000000140000000200000054000000200000000200000033D53981522A78408F186EB66FC55E40000000000000000033D53981522A78408F186EB66FC55E40000000000000000000000000000000000000000000000000000000000000F03F0C00000016000000020000C30C00000017000000FDFFFFFF0C00000012000000FF7F00000C00000012000000000000000C000000140000000200000054000000200000000200000047E5E7B604A97840FF04B1AD48875F40000000000000000047E5E7B604A97840FF04B1AD48875F40000000000000000000000000000000000000000000000000000000000000F03F0C00000016000000020000C30C00000017000000FDFFFFFF0C00000012000000FF7F00000C00000012000000000000000C00000014000000020000005400000020000000020000005B7C16FD2CA977401F929A53771F5E4000000000000000005B7C16FD2CA977401F929A53771F5E40000000000000000000000000000000000000000000000000000000000000F03F0C00000016000000020000C30C00000017000000FDFFFFFF0C00000012000000FF7F00000C00000012000000000000000C000000140000000200000054000000200000000200000062797C905E577840C1875C4B165C6140000000000000000062797C905E577840C1875C4B165C6140000000000000000000000000000000000000000000000000000000000000F03F080000001F000000",
'     "entmode": 2,
'     "nolinks": 0,
'     "color": 256,
'     "ltype_scale": 1.0,
'     "ltype_flags": 0,
'     "plotstyle_flags": 0,
'     "invisible": 0,
'     "linewt": 29,
'     "_subclass": "AcDbDimension",
'     "extrusion": [0.0, 0.0, 1.0],
'     "text_midpt": [380.92928572639323, 139.3416183844374],
'     "elevation": 0.0,
'     "flag1": 11,
'     "user_text": "",
'     "text_rotation": 0.0,
'     "horiz_dir": 0.0,
'     "ins_scale": [1.0, 1.0, 1.0],
'     "ins_rotation": 0.0,
'     "attachment": 5,
'     "lspace_style": 1,
'     "lspace_factor": 1.0,
'     "act_measurement": 26.17270411733045,
'     "clone_ins_pt": [0.0, 0.0],
'     "flag": 128,
'     "_subclass": "AcDbArcDimension",
'     "def_pt": [389.46058701155391, 138.87772148201296, 0.0],
'     "xline1_pt": [394.56365099510407, 126.11381094252646, 0.0],
'     "xline2_pt": [378.5734835508681, 120.49165811629108, 0.0],
'     "center_pt": [386.64514277068076, 123.08494339705997, 0.0],
'     "is_partial": 0,
'     "arc_start_param": 0.36533394824646,
'     "arc_end_param": 3.45245880810067,
'     "has_leader": 0,
'     "leader1_pt": [394.56365099510407, 126.11381094252646, 0.0],
'     "leader2_pt": [378.5734835508681, 120.49165811629108, 0.0],
'     "dimstyle": [5, 1, 57, 57],
'     "block": [5, 2, 4606, 4606]



' "entity": "DIMENSION_RADIUS",
'   "index": 296,
'   "type": 25,
'   "handle": [0, 4732],
'   "size": 145,
'   "bitsize": 1018,
'   "eed": [
'     {
'       "size": 30,
'       "handle": [5, 4701],
'       "code": 70,
'       "value": 387
'     },
'     {
'       "code": 70,
'       "value": 1
'     },
'     {
'       "code": 70,
'       "value": 388
'     },
'     {
'       "code": 40,
'       "value": 0.0
'     },
'     {
'       "code": 70,
'       "value": 390
'     },
'     {
'       "code": 40,
'       "value": 0.0
'     }
'   ],
'   "reactors": [
'     [4, 2, 4734, 4734]
'   ],
'   "xdicobjhandle": [3, 2, 4733, 4733],
'   "_subclass": "AcDbEntity",
'   "prev_entity": [8, 0, 0, 4731],
'   "next_entity": [10, 1, 32, 4764],
'   "layer": [5, 2, 5261, 5261],
'   "preview_exists": 0,
'   "entmode": 2,
'   "nolinks": 0,
'   "color": 256,
'   "ltype_scale": 1.0,
'   "ltype_flags": 0,
'   "plotstyle_flags": 0,
'   "invisible": 0,
'   "linewt": 29,
'   "_subclass": "AcDbDimension",
'   "extrusion": [0.0, 0.0, 1.0],
'   "text_midpt": [339.36338569594892, 172.70867755725541],
'   "elevation": 0.0,
'   "flag1": 11,
'   "user_text": "",
'   "text_rotation": 0.0,
'   "horiz_dir": 0.0,
'   "ins_scale": [1.0, 1.0, 1.0],
'   "ins_rotation": 0.0,
'   "attachment": 5,
'   "lspace_style": 1,
'   "lspace_factor": 1.0,
'   "act_measurement": 10.50494238347653,
'   "clone_ins_pt": [0.0, 0.0],
'   "flag": 128,
'   "_subclass": "AcDbRadialDimension",
'   "def_pt": [336.34758655818518, 168.24654323153257, 0.0],
'   "first_arc_pt": [344.00833947299708, 175.43449699170401, 0.0],
'   "leader_len": 0.0,
'   "dimstyle": [5, 1, 57, 57],
'  "block": [5, 2, 4735, 4735]


'    "entity": "DIMENSION_DIAMETER",
' "index": 303,
' "type": 26,
' "handle": [0, 4765],
' "size": 145,
' "bitsize": 1018,
' "eed": [
'   {
'     "size": 30,
'     "handle": [5, 4701],
'     "code": 70,
'     "value": 387
'   },
'   {
'     "code": 70,
'     "value": 1
'   },
'   {
'     "code": 70,
'     "value": 388
'   },
'   {
'     "code": 40,
'     "value": 0.0
'   },
'   {
'     "code": 70,
'     "value": 390
'   },
'   {
'     "code": 40,
'     "value": 0.0
'   }
' ],
' "reactors": [
'   [4, 2, 4767, 4767]
' ],
' "xdicobjhandle": [3, 2, 4766, 4766],
' "_subclass": "AcDbEntity",
' "prev_entity": [8, 0, 0, 4764],
' "next_entity": [10, 1, 14, 4779],
' "layer": [5, 2, 5261, 5261],
' "preview_exists": 0,
' "entmode": 2,
' "nolinks": 0,
' "color": 256,
' "ltype_scale": 1.0,
' "ltype_flags": 0,
' "plotstyle_flags": 0,
' "invisible": 0,
' "linewt": 29,
' "_subclass": "AcDbDimension",
' "extrusion": [0.0, 0.0, 1.0],
' "text_midpt": [379.65954790543469, 169.39468359475671],
' "elevation": 0.0,
' "flag1": 11,
' "user_text": "",
' "text_rotation": 0.0,
' "horiz_dir": 0.0,
' "ins_scale": [1.0, 1.0, 1.0],
' "ins_rotation": 0.0,
' "attachment": 5,
' "lspace_style": 1,
' "lspace_factor": 1.0,
' "act_measurement": 21.00988476695261,
' "clone_ins_pt": [0.0, 0.0],
' "flag": 128,
' "_subclass": "AcDbDiametricDimension",
' "first_arc_pt": [389.47625832969106, 165.46998685659418, 0.0],
' "def_pt": [369.2135290784824, 171.02309960647062, 0.0],
' "leader_len": 0.0,
' "dimstyle": [5, 1, 57, 57],
' "block": [5, 2, 4768, 4768]


'       "entity": "LARGE_RADIAL_DIMENSION",
' "index": 312,
' "type": 516,
' "handle": [0, 4860],
' "size": 1500,
' "bitsize": 11864,
' "preview_exists": 1,
' "eed": [
'   {
'     "size": 26,
'     "handle": [5, 23],
'     "code": 0,
'     "value": "DSTYLE"
'   },
'   {
'     "code": 2,
'     "value": 0
'   },
'   {
'     "code": 70,
'     "value": 50
'   },
'   {
'     "code": 40,
'     "value": 0.78539816339745
'   },
'   {
'     "code": 2,
'     "value": 1
'   },
'   {
'     "size": 30,
'     "handle": [5, 4701],
'     "code": 70,
'     "value": 387
'   },
'   {
'     "code": 70,
'     "value": 1
'   },
'   {
'     "code": 70,
'     "value": 388
'   },
'   {
'     "code": 40,
'     "value": 0.0
'   },
'   {
'     "code": 70,
'     "value": 390
'   },
'   {
'     "code": 40,
'     "value": 0.0
'   }
' ],
' "reactors": [
'   [4, 2, 4862, 4862]
' ],
' "xdicobjhandle": [3, 2, 4861, 4861],
' "_subclass": "AcDbEntity",
' "prev_entity": [8, 0, 0, 4859],
' "next_entity": [10, 1, 75, 4935],
' "layer": [5, 2, 5261, 5261],
' "preview_exists": 1,
' "preview_is_proxy": 0,
' "preview_size": 1288,
' "preview": "080500002A0000000C0000001300000000000000880000001D000000000000000000F03F0000000000000000000000000000000000000000000000000000000000000000000000000000F03F0000000000000000000000000000000000000000000000000000000000000000000000000000F03F0000000000000000000000000000000000000000000000000000000000000000000000000000F03F0C000000160000000A0000C30C00000017000000FDFFFFFF0C00000012000000FF7F0000540000002000000002000000BAD9F6F6E2467740449CA6B8251169400000000000000000E1FDE8858BC8764085F71FF956C06940000000000000000000000000000000000000000000000000000000000000F03F0C000000160000000A0000C30C00000017000000FDFFFFFF0C00000012000000FF7F0000540000002000000002000000E1FDE8858BC8764085F71FF956C06940000000000000000086F371713C417840AEC75419C8486A40000000000000000000000000000000000000000000000000000000000000F03F0C000000160000000A0000C30C00000017000000FDFFFFFF0C00000012000000FF7F000054000000200000000200000086F371713C417840AEC75419C8486A400000000000000000AC176400E5C27740F822CE59F9F76A40000000000000000000000000000000000000000000000000000000000000F03F0C000000160000000A0000C30C00000017000000FDFFFFFF0C00000012000000FE7F0000540000002000000002000000F7BB26F306CE774078AA9EA201FC6A4000000000000000006173A10DC3B77740789BFD10F1F36A40000000000000000000000000000000000000000000000000000000000000F03F0C00000016000000090000C30C00000017000000FDFFFFFF0C00000012000000FF7F00000C00000016000000090000C3A40000000B00000011461B2804A67740F6FFB729DA2E6B40000000000000000000000000000000000000000000000000000000000000F03F3116D0552E4CEA3FB816C1B49C3BE2BF00000000000000005231302C35300000060000000100000000000000000000409A9999999999E93F0000000000000000000000000000F03F0000000000000000000000000000000000000000726F6D616E732E736878005C000000C00C00000016000000020000C30C00000017000000FDFFFFFF0C00000012000000FF7F00000C00000012000000000000000C0000001400000002000000540000002000000002000000AC176400E5C27740F822CE59F9F76A400000000000000000AC176400E5C27740F822CE59F9F76A40000000000000000000000000000000000000000000000000000000000000F03F0C00000016000000020000C30C00000017000000FDFFFFFF0C00000012000000FF7F00000C00000012000000000000000C0000001400000002000000540000002000000002000000BAD9F6F6E2467740449CA6B8251169400000000000000000BAD9F6F6E2467740449CA6B825116940000000000000000000000000000000000000000000000000000000000000F03F0C00000016000000020000C30C00000017000000FDFFFFFF0C00000012000000FF7F00000C00000012000000000000000C0000001400000002000000540000002000000002000000B478ADFBE3847740995F3A898F046A400000000000000000B478ADFBE3847740995F3A898F046A40000000000000000000000000000000000000000000000000000000000000F03F080000001F000000",
' "entmode": 2,
' "nolinks": 0,
' "color": 256,
' "ltype_scale": 1.0,
' "ltype_flags": 0,
' "plotstyle_flags": 0,
' "invisible": 0,
' "linewt": 29,
' "_subclass": "AcDbDimension",
' "extrusion": [0.0, 0.0, 1.0],
' "text_midpt": [381.6653012244023, 214.72001678258115],
' "elevation": 0.0,
' "flag1": 10,
' "user_text": "",
' "text_rotation": 0.0,
' "horiz_dir": 0.0,
' "ins_scale": [1.0, 1.0, 1.0],
' "ins_rotation": 0.0,
' "attachment": 5,
' "lspace_style": 1,
' "lspace_factor": 1.0,
' "act_measurement": 10.50494238347625,
' "clone_ins_pt": [0.0, 0.0],
' "flag": 128,
' "_subclass": "AcDbRadialDimensionLarge",
' "def_pt": [388.81386432399268, 209.7637151214733, 0.0],
' "first_arc_pt": [380.1809085759985, 215.74918833027891, 0.0],
' "leader_len": 0.0,
' "ovr_center": [372.43041130472159, 200.53585464993569, 0.0],
' "jog_point": [376.3056599403601, 208.14252149010716, 0.0],
' "dimstyle": [5, 1, 57, 57],
' "block": [5, 2, 4863, 4863]


'      "entity": "DIMENSION_ORDINATE",
' "index": 319,
' "type": 20,
' "handle": [0, 4936],
' "size": 122,
' "bitsize": 876,
' "_subclass": "AcDbEntity",
' "prev_entity": [8, 0, 0, 4935],
' "next_entity": [10, 1, 9, 4945],
' "layer": [5, 2, 5261, 5261],
' "preview_exists": 0,
' "entmode": 2,
' "nolinks": 0,
' "color": 256,
' "ltype_scale": 1.0,
' "ltype_flags": 0,
' "plotstyle_flags": 0,
' "invisible": 0,
' "linewt": 29,
' "_subclass": "AcDbDimension",
' "extrusion": [0.0, 0.0, 1.0],
' "text_midpt": [339.406966706015, 201.3821301658075],
' "elevation": 0.0,
' "flag1": 11,
' "user_text": "",
' "text_rotation": 0.0,
' "horiz_dir": 0.0,
' "ins_scale": [1.0, 1.0, 1.0],
' "ins_rotation": 0.0,
' "attachment": 5,
' "lspace_style": 1,
' "lspace_factor": 1.0,
' "act_measurement": 126.38743121141022,
' "clone_ins_pt": [0.0, 0.0],
' "_subclass": "AcDbOrdinateDimension",
' "def_pt": [142.92093415289901, 73.80422276392108, 0.0],
' "feature_location_pt": [326.91019506733892, 200.19165397533129, 0.0],
' "leader_endpt": [335.5974428964912, 200.19165397533129, 0.0],
' "flag2": 0,
' "flag": 128,
' "dimstyle": [5, 1, 57, 57],
' "block": [5, 2, 4937, 4937]


' If lpcode = "2" Then mDim.bloque = lpvalue
' If lpcode = "10" Then mDim.p.Add(CFloat(lpvalue))
' If lpcode = "20" Then mDim.p.Add(CFloat(lpvalue))
' If lpcode = "11" Then mDim.p.Add(CFloat(lpvalue))
' If lpcode = "21" Then mDim.p.Add(CFloat(lpvalue))
' If lpcode = "70" Then mDim.tipo = CInt(lpvalue)
' If lpcode = "71" Then mDim.alineacion = CInt(lpvalue)
' If lpcode = "42" Then mDim.medida = CFloat(lpvalue)
' If lpcode = "42" Then mDim.texto = lpvalue
' If lpcode = "12" Then mDim.p.Add(CFloat(lpvalue))
' If lpcode = "13" Then mDim.p.Add(CFloat(lpvalue))
' If lpcode = "14" Then mDim.p.Add(CFloat(lpvalue))
' If lpcode = "15" Then mDim.p.Add(CFloat(lpvalue))
' If lpcode = "16" Then mDim.p.Add(CFloat(lpvalue))
' If lpcode = "26" Then mDim.p.Add(CFloat(lpvalue))
' If lpcode = "22" Then mDim.p.Add(CFloat(lpvalue))
' If lpcode = "23" Then mDim.p.Add(CFloat(lpvalue))
' If lpcode = "24" Then mDim.p.Add(CFloat(lpvalue))
' If lpcode = "25" Then mDim.p.Add(CFloat(lpvalue))
' If lpcode = "50" Then mDim.angulo = CFloat(lpvalue)
