' Gambas class file

' GauchoCAD
' A simple CAD made in Gambas
'
' Copyright (C) Ing Martin P Cristia
'
' This program is free software; you can redistribute it and/or modify
' it under the terms of the GNU General Public License as published by
' the Free Software Foundation; either version 3 of the License, or
' (at your option) any later version.
'
' This program is distributed in the hope that it will be useful,
' but WITHOUT ANY WARRANTY; without even the implied warranty of
' MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
' GNU General Public License for more details.
'
' You should have received a copy of the GNU General Public License
' along with this program; if not, write to the Free Software
' Foundation, Inc., 51 Franklin St, Fifth Floor,
' Boston, MA  02110-1301  USA
Create Static
'Fast

Public Const Gender As String = "Ray"
Public Const DrawingOrder As Integer = 1        ' 1 = draws first
Public Const HelperTrabajo As String = ("an infinite ray")
Public Const ParamType As String = "PP"                             ' that is Point, Point; could be Color Text, etc
Public Const ParamHelper As String = "Start point;Ray direction"
Public Const GAMBASCADENTITY As String = "EntityBase"
Public Const USEWITH As String = "clsEntityBuilder"
Public Const PointsToDraw As Integer = 1             ' minimal point requered for drawing something usefull
Public Const OrthogonalIgnored As Boolean = False
Public Const OrthogonalForced As Boolean = False
Public Const ParamDefault As String = " "
Public Const StretchAble As Boolean = True           ' Si lo puedo deformar
Public Selected As Boolean
Public ForDeletion As Boolean = True        ' this must be falsed in Finish
Public DrawAble As Boolean = False          ' True si durante la construccion ya tiene suficientes elementos para poder hacer una representacion digna
Public Visible As Boolean = True            ' si esta entidad puede ser mostrada independientmente
Public Finished As Boolean = False          ' colocar en true cuando se llegue a completar
Public StepsDone As Integer                 ' esto lo cambia cls ElementBuilder durante la construccion

Private p2 As New Float[]

' JSON and DXF Read/Export
Public Const JSON_Reading As Boolean = True
Public Const JSON_Export As Boolean = False

Public Const DXF_Reading As Boolean = True
Public Const DXF_Export As Boolean = True


Private Sub MakeRay(p As Float[])

  p2.Clear

  p2.Add(P[0])
  p2.Add(P[1])

  p2.Add((P[2] - p[0]) * 1e10)
  p2.Add((P[3] - p[1]) * 1e10)

  p2.Add(P[0])
  p2.Add(P[1])

  p2.Add((P[2] - p[0]) * -1e10)
  p2.Add((P[3] - p[1]) * -1e10)


End


Public Sub Translate(e As Entity, dX As Float, dY As Float, Optional OnlySelected As Boolean = False)

  Dim i As Integer

  If OnlySelected Then

    For i = 0 To e.Psel.Max
      If e.Psel[i] Then

        e.P[i * 2] += dx
        e.P[i * 2 + 1] += dy

      Endif
    Next

  Else

    puntos.Translate(e.p, dx, dy)
  Endif

End

Public Sub Rotate(e As Entity, radians As Float)

  puntos.Rotate(e.p, radians)

End

Public Sub Scale(e As Entity, sX As Float, sY As Float)

  Dim i As Integer

  For i = 0 To e.p.max Step 2

    e.P[i] = e.P[i] * sX
    e.P[i + 1] = e.P[i + 1] * sY

  Next

End

Public Sub Draw(oE As Entity)

  oE.ColorToPaint = gcd.GetGBColor(oE.colour, oE.Layerid)

  MakeRay(oe.p)

  GLplus.Lines(p2, oE.ColorToPaint, oE.LineWidth, oE.LineType)



End

'' A fat version of the line
Public Sub DrawSelected(oE As Entity)

  Dim i As Integer
  Dim iLineType As Integer

  If oe.LineType = gcd.stiDashed Then iLineType = 0 Else iLineType = gcd.stiDashed
  MakeRay(oe.p)

  GLplus.Lines(p2, Starter.flgWindowBackColor, oE.LineWidth, iLineType)

  GLplus.Lines(p2, gcd.ColorForSelected, oE.LineWidth, oe.LineType)

End
'' A fat version of the line

Public Sub DrawRemark(oE As Entity)

  If Not oE.Visible Then Return

  MakeRay(oe.P)
  If oe.Selected Then
    GLplus.Lines(P2, Starter.flgWindowBackColor, oE.LineWidth + 2, gcd.stiDashed)
    GLplus.Lines(P2, gcd.ColorForSelected, oE.LineWidth + 2, oE.LineType)
  Else
    GLplus.Lines(P2, Starter.flgWindowBackColor, oE.LineWidth, gcd.stiDashed)
    GLplus.Lines(P2, oE.ColorToPaint, oE.LineWidth + 2, oE.LineType)
  Endif

End

'' The paint version of the entity
Public Function Draw2(oE As Entity)

  If Not oE.Visible Then Return

  paint.LineWidth = oE.LineWidth '' / gcd.CurrentDrawing.ScaleZoom / gcd.ScaleLines

  paint.brush = Paint.Color(oE.ColorToPaint)
  paint.MoveTo(oE.p[0], oE.p[1])
  paint.LineTo(oE.p[2], oE.p[3])
  paint.Stroke

End

'' Creo los puntos de interes
'' Build point of interest

Public Function BuildPOI(oE As Entity, Optional arrIndex As Integer = -1) As Integer

  If arrIndex < 0 Then arrIndex = gcd.CurrentDrawing.arrEntities.Max       ' si este valor no es provisto , estos POI son de la ultima entidad

  oe.PoiPoints.Clear
  oe.PoiType.Clear

  ' points: end-mid-end
  oe.poiPoints.insert([oE.p[0], oE.p[1]])
  oe.poiType.Add(gcd.poiEndPoint)

  oe.poiPoints.insert([(oE.P[0] + oE.P[2]) / 2, (oE.P[1] + oE.P[3]) / 2])   ' mid
  oe.poiType.Add(gcd.poiMidPoint)
  'gcd.CurrentDrawing.poiEntities.Add(arrIndex)

  oe.poiPoints.insert([oE.p[2], oE.p[3]])
  oe.poiType.Add(gcd.poiEndPoint)
  'gcd.CurrentDrawing.poiEntities.Add(arrIndex)

  ' line
  ' gcd.CurrentDrawing.poiLines.insert([oE.p[0], oE.p[1], oE.p[2], oE.p[3]])
  ' gcd.CurrentDrawing.poiLinesEntities.Add(arrIndex)
  'gcd.CurrentDrawing.poiLinesRelPoint.Insert([0, 1])

End

' This function will return False if the element couldn't be created for some reason: bad or incomple user input
' True means all is good, False will instruct the clsEntityBuilder to delete it
Public Sub Finish(oE As Entity, Optional ParamsDone As Integer = -1) As Boolean

  'Print "Finish en EntityBase"
  'CreatePolygon(oe)

  ' If Abs(oe.P[2]) < 1e10 Then oe.p[2] *= 1e10
  ' If Abs(oe.P[3]) < 1e10 Then oe.p[3] *= 1e10
  ' If oe.P.Count < 4 Then
  '   oe.P.Add(oe.P[0])
  '   oe.P.Add(oe.P[1])
  '
  '   oe.P.Add(oe.P[2] * -1e10)
  '   oe.P.Add(oe.P[3] * -1e10)
  ' Else
  '    If Abs(oe.P[6]) < 1e10 Then oe.p[6] *= 1e10
  '    If Abs(oe.P[7]) < 1e10 Then oe.p[7] *= 1e10
  '
  '
  ' Endif

  BuildPOI(oe)

  ' busco el tipo de linea, si hace falta
  If oE.LineTypeName = "Dashed" Then oE.LineType = 1
  ' tareas finales de armado del objeto

  oE.psel.resize(oE.p.count / 2)
  oE.ForDeletion = False
  oE.DrawAble = True
  oE.Selected = False
  oE.Finished = True

  If Not True Then

    oE.ForDeletion = True
    oE.DrawAble = False

  End If

End

' Importo los datos que puedo procesar de una coleccion y genero un Entity para ser agregado a un array
Public Function ImportJsonCol(c As JSONCollection, e As Entity) As Boolean

  'Common Pack
  '   e.dwg = c
  ' e.dwg["index"] = c["index"]
  ' e.dwg["type"] = c["type"]
  ' e.dwg["handle"] = c["handle"]
  ' e.dwg["size"] = c["size"]
  ' e.dwg["bitsize"] = c["bitsize"]
  ' If c.Exist("ownerhandle") Then
  '   e.dwg["ownerhandle"] = c["ownerhandle"]
  ' Endif
  ' e.dwg["_subclass"] = c["_subclass"]
  ' e.dwg["prev_entity"] = c["prev_entity"]
  ' e.dwg["next_entity"] = c["next_entity"]
  ' e.dwg["layer"] = c["layer"]
  ' e.dwg["preview_exists"] = c["preview_exists"]
  ' e.dwg["entmode"] = c["entmode"]
  ' e.dwg["nolinks"] = c["nolinks"]
  ' e.dwg["color"] = 0
  ' e.dwg["ltype_scale"] = 1.0
  ' e.dwg["ltype_flags"] = 1
  ' e.dwg["plotstyle_flags"] = 0
  ' e.dwg["invisible"] = 0
  ' e.dwg["linewt"] = 30

  e.ClassHandler = Me
  e.P.Add(c["start"][0])
  e.P.Add(c["start"][1])
  e.P.Add(c["end"][0])
  e.P.Add(c["end"][1])

  Return True

End

' Exporto los datos de una Entity a una coleccion para ser guardados
'Public Function ExportJsonCol(e As Entity) As Collection
' Public Function dwg(e As Entity) As JSONCollection
'
'   Dim n As New JSONCollection
'   'Common fields
'   n["entity"] = "LINE"
'   n["index"] = 44
'   n["type"] = 19
'   n["handle"] = [0, e.Handle]
'   n["size"] = 43
'   n["bitsize"] = 283
'   n["ownerhandle"] = [12, 1, 3, 48]
'   n["_subclass"] = "AcDbEntity"
'   n["prev_entity"] = [8, 0, 0, 50]
'   n["next_entity"] = [4, 0, 0, 0]
'   n["layer"] = [5, 1, 6, 6]
'   n["preview_exists"] = 0
'   n["entmode"] = 0
'   n["nolinks"] = 0
'   n["color"] = e.colour
'   n["ltype_scale"] = 1.0
'   n["ltype_flags"] = 1
'   n["plotstyle_flags"] = 0
'   n["invisible"] = 0
'   n["linewt"] = 30
'   n["_subclass"] = "AcDbLine"
'   n["z_is_zero"] = 1
'   n["start"] = [-0.5, 0.0, 0.0]
'   n["end"] = [-1.0, 0.0, 0.0]
'   n["thickness"] = 0.000000
'   n["extrusion"] = [0.0, 0.0, 1.0]
'
'   n.Add(e.colour, "color")
'   'puntos
'   n["start"] = [e.P[0], e.P[1]]
'   n["end"] = [e.P[2], e.P[3]]
'
'   n.add(e.LineWidth * 100, "linewt")
'
'   ' etc
'   Return n
'
' End

'      "entity": "LINE",
'      "index": 399,
'      "type": 19,
'      "handle": [0, 254700],
'      "size": 42,
'      "bitsize": 283,
'      "ownerhandle": [12, 1, 7, 254693],
'      "_subclass": "AcDbEntity",
'      "layer": [5, 2, 16846, 16846],
'      "preview_exists": 0,
'      "entmode": 0,
'      "nolinks": 1,
'      "color": 256,
'      "ltype_scale": 1.0,
'      "ltype_flags": 0,
'      "plotstyle_flags": 0,
'      "invisible": 0,
'      "linewt": 29,
'      "_subclass": "AcDbLine",
'      "z_is_zero": 1,
'      "start": [2914.34678481761921, 1641.03048722972585, 0.0],
'      "end": [2914.3721519990504, 1641.03048722972585, 0.0],
'      "thickness": 0.000000,
'      "extrusion": [0.0, 0.0, 1.0]
Public Sub ExportDXF(e As Entity, hFile As File)

  Print #hFIle, "  0"                       ' Entity type
  Print #hFIle, "RAY"
  clsEntities.DXFExportCommon(e, hFile)
  Print #hFIle, "100"                     ' Subclass marker
  Print #hFIle, "AcDbLine"
  Print #hFIle, " 10"                      ' X0
  Print #hFIle, CStr(e.p[0])
  Print #hFIle, " 20"                      ' Y0
  Print #hFIle, CStr(e.p[1])
  Print #hFIle, " 11"                      ' X1
  Print #hFIle, CStr(e.p[2])
  Print #hFIle, " 21"                      ' Y1
  Print #hFIle, CStr(e.p[3])


End


Public Function ImportDXF(e As Entity, sClaves As String[], sValues As String[]) As Boolean

  Dim i As Integer

  For i = 0 To sClaves.Max

    If sClaves[i] = "10" Then e.P.Add(CFloat(sValues[i]))
    If sClaves[i] = "20" Then e.P.Add(CFloat(sValues[i]))
    If sClaves[i] = "11" Then e.P.Add(CFloat(sValues[i]))
    If sClaves[i] = "21" Then e.P.Add(CFloat(sValues[i]))

  Next

End
